baseurl: /blog

title: Michael Samoylenko - Blog
description: Blog
twitter_username: m_samoylenko
github_username: samoylenko

show_excerpts: true
excerpt_separator: <!--more-->

theme: minima
plugins:
  - jekyll-feed

exclude:
  - README.md
  - CNAME
